/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica;

import CapaLogica.Administrador;
import CapaLogica.Docente;
import CapaLogica.Inasistencia_docente;
import CapaLogica.FachadaLogica;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana de consulta pública de inasistencias docentes.
 * Pertenece a la capa gráfica.
 */
public class Consultar extends javax.swing.JFrame {

    private final FachadaLogica fachada;

    public Consultar() {
        this.fachada = new FachadaLogica();
        initComponents();
        setLocationRelativeTo(null);
        configurarTabla();
        cargarTablaLicencias(fachada.obtenerTodas());
    }

    /**
     * Configura el modelo de la tabla para mostrar las inasistencias.
     */
    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelo.setColumnIdentifiers(new String[]{"ID", "Docente", "Grupo", "Turno", "Tipo", "Motivo", "F. Inicio", "F. Fin", "Administrativo"});
        tablaLicencias.setModel(modelo);
    }

    /**
     * Llena la tabla con los registros recibidos desde la fachada lógica.
     *
     * @param registros listado de inasistencias a mostrar.
     */
    private void cargarTablaLicencias(List<Inasistencia_docente> registros) {
        DefaultTableModel modelo = (DefaultTableModel) tablaLicencias.getModel();
        modelo.setRowCount(0);

        if (registros == null || registros.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No se encontraron inasistencias registradas.",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        for (Inasistencia_docente registro : registros) {
            Docente docente = registro.getDocente();
            String nombreDocente = docente != null ? docente.getNombreCompleto() : null;
            if (nombreDocente == null || nombreDocente.isBlank()) {
                nombreDocente = registro.getCiDocente();
            }

            Administrador admin = registro.getAdministrador();
            String nombreAdmin = admin != null ? admin.getNombreCompleto() : null;
            if (nombreAdmin == null || nombreAdmin.isBlank()) {
                nombreAdmin = registro.getCiAdministrativo();
            }

            modelo.addRow(new Object[]{
                registro.getId(),
                nombreDocente,
                docente != null ? docente.getGrupo() : null,
                docente != null ? docente.getTurno() : null,
                registro.getTipo(),
                registro.getMotivo(),
                registro.getFechaInicio(),
                registro.getFechaFin(),
                nombreAdmin
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLicencias = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnVerHoy = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Consulte inasistencias");

        tablaLicencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Docente", "Grupo", "Turno", "Tipo", "Motivo", "Desde", "Hasta", "Administrativo"
            }
        ));
        jScrollPane2.setViewportView(tablaLicencias);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        btnVerHoy.setText("Ver de hoy");
        btnVerHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHoyActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefrescar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerHoy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnVolver)
                    .addComponent(btnRefrescar)
                    .addComponent(btnVerHoy))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Regresa a la ventana de bienvenida.
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
        setVisible(false);
        Bienvenida in = new Bienvenida();
        in.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * Refresca la tabla con todos los registros disponibles.
     */
    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        cargarTablaLicencias(fachada.obtenerTodas());
    }//GEN-LAST:event_btnRefrescarActionPerformed

    /**
     * Muestra únicamente los registros vigentes en la fecha actual.
     */
    private void btnVerHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHoyActionPerformed
        cargarTablaLicencias(fachada.obtenerDeHoy());
    }//GEN-LAST:event_btnVerHoyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnVerHoy;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaLicencias;
    // End of variables declaration//GEN-END:variables
}
